import Head from 'next/head'
import styles from '@/styles/Home.module.sass'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next/React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}